# These values will range from -1 to 1 to represent the thruster values.
# -1 represents full speed reverse, 1 represents full speed ahead,
# 0 represents dead stop, floats represent intermediary values.
Header header

float32 thruster_topfront
float32 thruster_topback
float32 thruster_topleft
float32 thruster_topright
float32 thruster_frontleft
float32 thruster_frontright
float32 thruster_backleft
float32 thruster_backright
